# Generated by Django 4.0.3 on 2022-06-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_about_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forhire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photographytypes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
