# Generated by Django 4.0.3 on 2022-06-01 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_forhire_profile_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='forhire',
            new_name='availableforHire',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='locationAvailable',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='photographytypes',
            new_name='photographySpecialty',
        ),
    ]
