# Generated by Django 4.0.3 on 2022-04-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_approved_photo_photographer'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='publishdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
