# Generated by Django 4.0.3 on 2022-04-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_photo_slug_photo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
