# Generated by Django 4.0.3 on 2022-05-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_remove_photo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocategory',
            name='description',
            field=models.CharField(default='placeholder', max_length=300),
            preserve_default=False,
        ),
    ]
