# Generated by Django 4.0.3 on 2022-05-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_photo_camera_photo_focal_photo_iso_photo_shutter'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='apeture',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
