# Generated by Django 4.0.3 on 2022-05-11 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_photo_apeture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='apeture',
            new_name='aperture',
        ),
    ]
