# Generated by Django 4.0.3 on 2022-05-31 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0012_rename_apeture_photo_aperture'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='likes',
            field=models.ManyToManyField(related_name='blog_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
