# Generated by Django 4.0.3 on 2022-06-01 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_remove_photo_likes_photo_photolikes_photocomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photolikes',
        ),
        migrations.DeleteModel(
            name='PhotoComment',
        ),
    ]
